### ISSUE TITLE
user.displayName is undefined

### ISSUE THREAD

**Issue by m98jk** [Vuka951/tutorial-code#3]
Hi Vuka ,
Thank you for your great tutorials and the good explanation . 

when I tried to do the same as the code in the tutorial , it shows me an error in [user.displayName](https://github.com/Vuka951/tutorial-code/blob/master/express-google-oauth2/done/index.js#L41)  that is undefined 
and when I tried to log the user it also show undefined .

can you please help me understand the error

**Comment by Vuka951** [comment]
Hey,
i assume ur talking about the express google oAuth 2.0 tutorial.
The code for that is in this repo and you can check if it is the same.(you'll need to change the api keys)
You can also copy it and try it.
Reason why its saying undefined is that your not passing it to the request as i did in the tutorial prob missing a line or 2 of code.
Check the repo if that dont work, copy the exact same code (change the api keys) and try it.
You prob just missed something.
Code: https://github.com/Vuka951/tutorial-code/tree/master/express-google-oauth2/done

Also this section is for issues with the code in the actual repo only. (as in code that is in the repo doesnt work.
