### ISSUE TITLE
 flask-google-oauth2 issue

### ISSUE THREAD

**Issue by aserenil** [Vuka951/tutorial-code#86]
There may have been a change since your code was added.  I tried your flask-google-oauth2 tutorial code. 

I was getting this error:
`RuntimeError: Missing "jwks_uri" in metadata`

I added this line to the oauth.register:
`server_metadata_url='https://accounts.google.com/.well-known/openid-configuration'`

Then this error occurred:
`authlib.jose.errors.InvalidClaimError: invalid_claim: Invalid claim "iss"`

I had to remove openid from client_kwargs to get it to work.

Did I miss anything?

**Comment by abhibansal60** [comment]
Fixed in [PR 87](https://github.com/Vuka951/tutorial-code/pull/87) as per https://stackoverflow.com/a/74835889/4461527
